MAPPER_METADATA = {
    "person": ["groom", "scuba_diver", "ballplayer"],
    "bicycle": ["mountain_bike"],
    "car": [
        "sports_car",
        "limousine",
        "racer",
        "convertible",
        "jeep",
        "cab",
    ],
    "motorcycle": ["moped", "motor_scooter"],
    "airplane": ["airliner", "warplane"],
    "bus": ["school_bus", "trolleybus"],
    "train": ["steam_locomotive"],
    "truck": [
        "trailer_truck",
        "fire_engine",
        "garbage_truck",
        "moving_van",
        "tow_truck",
        "tank",
    ],
    "boat": [
        "canoe",
        "catamaran",
        "yawl",
        "gondola",
        "paddlewheel",
        "schooner",
        "pirate",
        "airship",
        "submarine",
    ],
    "traffic_light": ["traffic_light"],
    "fire_hydrant": [],
    "street_sign": ["street_sign"],
    "stop_sign": ["street_sign"],
    "parking_meter": ["parking_meter"],
    "bench": ["park_bench"],
    "bird": [
        "cock",
        "hen",
        "ostrich",
        "brambling",
        "goldfinch",
        "robin",
        "bulbul",
        "jay",
        "magpie",
        "chickadee",
        "water_ouzel",
        "bald_eagle",
        "vulture",
        "great_grey_owl",
    ],
    "cat": [
        "Egyptian_cat",
        "tiger_cat",
        "Persian_cat",
        "Siamese_cat",
        "tabby",
        "lynx",
    ],
    "dog": [
        "Chihuahua",
        "Japanese_spaniel",
        "Maltese_dog",
        "Pekinese",
        "Shih-Tzu",
        "Blenheim_spaniel",
        "papillon",
        "toy_terrier",
        "Rhodesian_ridgeback",
        "Afghan_hound",
        "basset",
        "beagle",
        "bloodhound",
        "bluetick",
    ],
    "horse": ["sorrel", "zebra", "Appenzeller"],
    "sheep": [
        "ram",
        "bighorn",
        "ibex",
        "impala",
        "gazelle",
        "Arabian_camel",
        "llama",
    ],
    "cow": ["ox", "water_buffalo", "bison"],
    "elephant": ["Indian_elephant", "African_elephant"],
    "bear": ["brown_bear", "American_black_bear", "ice_bear", "sloth_bear"],
    "zebra": ["zebra"],
    "giraffe": ["giraffe"],
    "hat": ["cowboy_hat", "sombrero"],
    "backpack": ["backpack"],
    "umbrella": ["umbrella"],
    "shoe": ["running_shoe"],
    "eye_glasses": ["sunglasses"],
    "handbag": ["handbag"],
    "tie": ["tie", "Windsor_tie"],
    "suitcase": ["suitcase"],
    "frisbee": [],
    "skis": [],
    "snowboard": [],
    "sports_ball": ["soccer_ball", "rugby_ball", "tennis_ball", "basketball"],
    "kite": [],
    "baseball_bat": [],
    "baseball_glove": [],
    "skateboard": [],
    "surfboard": [],
    "tennis_racket": [],
    "bottle": ["water_bottle", "beer_bottle", "wine_bottle", "pop_bottle"],
    "plate": ["plate"],
    "wine_glass": [],
    "cup": ["coffee_mug", "cup"],
    "fork": [],
    "knife": [],
    "spoon": [],
    "bowl": ["soup_bowl"],
    "banana": ["banana"],
    "apple": ["Granny_Smith"],
    "sandwich": [],
    "orange": ["orange"],
    "broccoli": [],
    "carrot": [],
    "hot_dog": [],
    "pizza": [],
    "donut": [],
    "cake": [],
    "chair": ["folding_chair", "rocking_chair"],
    "couch": ["studio_couch"],
    "potted_plant": ["potted_plant"],
    "bed": ["four-poster"],
    "mirror": ["mirror"],
    "dining_table": ["dining_table"],
    "window": ["window_shade"],
    "desk": ["desk"],
    "toilet": ["toilet_seat"],
    "door": ["door"],
    "tv": ["television"],
    "laptop": ["laptop"],
    "mouse": ["computer_mouse"],
    "remote": ["remote_control"],
    "keyboard": ["keyboard"],
    "cell_phone": ["cellular_telephone"],
    "microwave": ["microwave"],
    "oven": ["oven"],
    "toaster": ["toaster"],
    "sink": ["washbasin"],
    "refrigerator": ["refrigerator"],
    "blender": [],
    "book": ["book_jacket"],
    "clock": ["wall_clock"],
    "vase": ["vase"],
    "scissors": ["scissors"],
    "teddy_bear": ["teddy"],
    "hair_drier": ["hair_dryer"],
    "toothbrush": ["toothbrush"],
    "hair_brush": ["hair_slide"],
}
